services:
  - type: web
    name: mushroom-classifier-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 8000 